#!/usr/bin/env bash

read -p "Is this computer running OSX Lion (10.7)? [y/n] " lion

echo "Checking for SSH key, generating one if it doesn't exist ..."
  [[ -f ~/.ssh/id_rsa.pub ]] || ssh-keygen -t rsa

echo "Copying public key to clipboard. Paste it into your Github account ..."
  [[ -f ~/.ssh/id_rsa.pub ]] && cat ~/.ssh/id_rsa.pub | pbcopy
  open https://github.com/account/ssh

echo "Installing Homebrew, a good OS X package manager ..."
  /usr/bin/ruby -e "$(/usr/bin/curl -fksSL https://raw.github.com/mxcl/homebrew/master/Library/Contributions/install_homebrew.rb)"
  brew update

echo "Put Homebrew location earlier in PATH ..."
  echo "
# recommended by brew doctor
export PATH='/usr/local/bin:$PATH'" >> ~/.bash_profile
  source ~/.bash_profile

echo "Installing Git, a good version control system ..."
  brew install git

echo "Installing Postgres, a good open source relational database ..."
  brew install postgres --no-python
  brew info postgres

echo "Postgres set up"  
  initdb /usr/local/var/postgres

if [ $lion == "Y" -o $lion == "y" ] ; then
  echo "Lion comes with a version of postgres already installed and uses those binaries by default this is a fix for that"
    curl http://nextmarvel.net/blog/downloads/fixBrewLionPostgres.sh | sh
fi

echo "Installing Redis, a good key-value database ..."
  brew install redis

echo "Installing ack, a good way to search through files ..."
  brew install ack

echo "Installing tmux, a good way to save project state and switch between projects ..."
  brew install tmux

echo "Installing ImageMagick, good for cropping and re-sizing images ..."
  brew install imagemagick

echo "Installing QT, used by Capybara Webkit for headless Javascript integration testing ..."
  brew install qt

echo "Installing Node.js, a good platform for event-driven applications using server side javascript ..."
  brew install node

echo "Installing ssh-copy-id, good for copying your ssh key to servers ..."
  brew install ssh-copy-id

echo "Installing rbenv, a good ruby version manager ..."
  brew install rbenv

echo "Put rbenv in PATH and rbenv init in shell ..."
  echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bash_profile
  echo 'eval "$(rbenv init -)"' >> ~/.bash_profile
  source ~/.bash_proile

echo "Installing ruby-build, good for automating ruby installs alongside rbenv ..."
  brew install ruby-build

curl -Os https://raw.github.com/molawson/laptop/master/ruby ; bash ruby
curl -Os https://raw.github.com/molawson/laptop/master/heroku ; bash heroku
